import { SlicerAdapter, SlicerMetadata } from "./slicerAdapter";

export class MockSlicerAdapter implements SlicerAdapter {
  async slice(stlFilePath: string): Promise<SlicerMetadata> {
    console.log(`[MockSlicerAdapter] Slicing file: ${stlFilePath}`);

    // Simulate a delay as if a real slicer is running
    await new Promise(resolve => setTimeout(resolve, 2000));

    const mockLog = `
    ; generated by MockSlicer v1.0
    ;
    ; file: ${stlFilePath}
    ; filament used [mm] = 8560.4
    ; filament used [g] = 25.7
    ; estimated printing time = 1h 45m 30s
    ; layer_height = 0.2
    ; infill_percentage = 20
    ; support_material = yes
    ; bounding_box = 50x80x110
    `;

    const metadata: SlicerMetadata = {
      estimatedTime: 6330, // 1h 45m 30s
      materialGrams: 25.7,
      filamentLength: 8560.4,
      layerCount: 550, // 110 / 0.2
      infillPercent: 20,
      boundingBox: "50x80x110",
      supportUsage: true,
      rawLog: mockLog,
    };

    console.log(`[MockSlicerAdapter] Slicing complete.`);
    return metadata;
  }
}
